# Ripped from https://github.com/JoeyMckenzie/realworld-rust-axum-sqlx/blob/main/Makefile.toml

[env] ## tells cargo make that we're in the context of a Cargo workspace
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

[tasks.dev]
install_crate="cargo-watch"
cwd = "./crates/conduit-bin"
command = "cargo"
args = ["watch", "-x", "clippy", "-x", "run"]
dependencies = ["postgres"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.migrate] ## ensure Postgres is running, the container has a bit of warmup time causing migrations to fail
cwd = "."
install_crate = "sqlx"
command = "sqlx"
args = ["migrate", "run"]
dependencies = ["postgres"]